name: CI
on: [push, pull_request]

jobs:
  doc:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust-toolchain: [nightly]
        targets: [riscv64gc-unknown-none-elf]
    permissions:
      contents: write
    env:
      default-branch: ${{ format('refs/heads/{0}', github.event.repository.default_branch) }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: ${{ matrix.rust-toolchain }}
          components: rust-src, clippy, rustfmt
          targets: ${{ matrix.targets }}
      - name: Check rust version
        run: rustc --version --verbose
      - name: Check code format
        run: cargo fmt --all -- --check
      - name: Clippy
        run: cargo clippy --target ${{ matrix.targets }} -- -A clippy::new_without_default
      - name: Build
        run: cargo build --target ${{ matrix.targets }}
      - name: Build docs
        continue-on-error: ${{ github.ref != env.default-branch && github.event_name != 'pull_request' }}
        run: |
          cargo doc --no-deps --target ${{ matrix.targets }}
          printf '<meta http-equiv="refresh" content="0;url=%s/index.html">' $(cargo tree | head -1 | cut -d' ' -f1) > target/riscv64gc-unknown-none-elf/doc/index.html
      - name: Deploy to Github Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          single-commit: true
          branch: gh-pages
          folder: target/riscv64gc-unknown-none-elf/doc
