[build]
target = "riscv64imac-unknown-none-elf"

[target.'cfg(target_os = "none")']
runner = "./test.sh"
rustflags = [
    "-Clink-arg=-Tlinker-riscv64.ld",
    "-Cforce-frame-pointers=yes",
    '--cfg=board="qemu"',
]